import Vue from 'vue'
import colors from 'vuetify/lib/util/colors'
import '@mdi/font/css/materialdesignicons.css'
import { mdiWarehouse } from '@mdi/js';
import { mdiPrinterPos } from '@mdi/js';

import Vuetify, {
	VApp,
	VAppBar,
	VAppBarNavIcon,
	VToolbar,
	VToolbarItems,
	VToolbarTitle,
	VList,
    VListGroup,
    VListItem,
    VListItemAction,
    VListItemActionText,
    VListItemAvatar,
    VListItemContent,
    VListItemGroup,
    VListItemIcon,
    VListItemSubtitle,
    VListItemTitle,
    VMenu,
	VBtn,
	VIcon,
	VContainer,
    VCol,
    VRow,
    VSpacer,
    VLayout,
    VFlex,
    VContent,
    VCard,
    VCardTitle,
    VCardActions,
    VCardText,
    VTextField,
    VCheckbox,
    VNavigationDrawer,
    VDataTable,
    VDataTableHeader,
    VEditDialog,
    VAlert,
    VImg,
    VStepper,
    VStepperContent,
    VStepperStep,
    VStepperHeader,
    VStepperItems,
    VDialog,
    VForm,
    VDivider,
    VSnackbar,
    VSelect,
    VTooltip,
    VSwitch,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelContent,
    VChip,
    VFileInput,
    VProgressLinear,
    VAutocomplete,
} from 'vuetify/lib'

Vue.use(Vuetify, {
	components: {
		VApp,
		VAppBar,
		VAppBarNavIcon,
		VToolbar,
		VToolbarItems,
		VToolbarTitle,
		VList,
	    VListGroup,
	    VListItem,
	    VListItemAction,
	    VListItemActionText,
	    VListItemAvatar,
	    VListItemContent,
	    VListItemGroup,
	    VListItemIcon,
	    VListItemSubtitle,
	    VListItemTitle,
	    VMenu,
		VBtn,
		VIcon,
		VContainer,
	    VCol,
	    VRow,
	    VSpacer,
	    VLayout,
	    VFlex,
	    VContent,
	    VCard,
	    VCardTitle,
	    VCardActions,
	    VCardText,
	    VTextField,
	    VCheckbox,
	    VNavigationDrawer,
	    VDataTable,
	    VDataTableHeader,
	    VEditDialog,
	    VAlert,
	    VImg,
	    VStepper,
	    VStepperContent,
	    VStepperStep,
	    VStepperHeader,
	    VStepperItems,
	    VDialog,
	    VForm,
	    VDivider,
	    VSnackbar,
	    VSelect,
	    VTooltip,
	    VSwitch,
	    VExpansionPanels,
	    VExpansionPanel,
    	VExpansionPanelContent,
    	VChip,
    	VFileInput,
    	VProgressLinear,
    	VAutocomplete,
	},
})
const opts = {
	icons: {
    	iconfont: 'mdi', // 'mdi' || 'mdiSvg' || 'md' || 'fa' || 'fa4'
  	},
  	theme: {
		dark: false,
		themes: {
			light: {
				primary: colors.teal.darken2,
			},
			dark: {
				primary: colors.teal.darken2,
			},
		},
	},
}

export default new Vuetify(opts)